@startuml create-post-diagram
actor User
User -> PostResource: create post
PostResource -> PostService: create post
alt success
    PostResource <-- PostService: success
    User <-- PostResource: success
else failure
    PostResource <-- PostService: failure
    User <-- PostResource
end
@enduml